FORMAT: 1A
HOST: http://localhost:13511/Products/api/

# ProductOrders

Sistema que permite generar y consultar ordenes de productos para clientes.

## Metodos del servicio [/getOrders/idCustomer/4/initDate/2017-09-21/finalDate/2017-10-22]

###  Listar ordenes por cliente [GET]

Crear​ ​una​ ​órden​ para un cliente con hasta máximo 5 productos 
(sólo algunos productos están permitidos por cliente).

+ Response 200 (application/json)
    + Headers

            Location: /questions/2

    + Body
    
            [
                {
                "id":35,
                "deliveryAddress":"Calle 12 N 40-31",
                "creationDate":"2017-10-22",
                "orderDetails":[{
                    "id":67,
                    "product":{"id":1,"name":"Producto Uno"},
                    "amount":3,
                    "price":30000
                },{
                    "id":68,
                    "product":{"id":2,"name":"Producto Dos"},
                    "amount":2,
                    "price":15000
                }]},
                {
                "id":36,
                "deliveryAddress":"Calle 12 N 40-31",
                "creationDate":"2017-10-22",
                "orderDetails":[{
                    "id":69,
                    "product":{"id":1,"name":"Producto Uno"},
                    "amount":3,
                    "price":30000
                },{
                    "id":70,
                    "product":{"id":2,"name":"Producto Dos"},
                    "amount":2,"price":15000
                }]}
            ]

### Listar ordenes por cliente [POST]

Listar ​las​ órdenes de un cliente por un rango de fechas. 
Retorna el codigo de respuesta y un mensaje, si es exitoso, el 
mensaje es el Id de la orden, en caso contrario es el error ocurrido.

+ Request (application/json)
        
    + Body
        
            {
              "deliveryAddress": "Calle 12 N 40-31",
              "customer": {
                "id": 5
              },
              "orderDetails": [
                {
                  "product": {
                    "id": 2
                  },
                  "amount": 1,
                  "price": 157000
                },
                {
                  "product": {
                    "id": 3
                  },
                  "amount": 2,
                  "price": 19000
                },
                {
                  "product": {
                    "id": 4
                  },
                  "amount": 2,
                  "price": 23000
                }
              ]
            }

+ Response 200 (application/json)

    + Body

            {
                "responseCode": "00",
                "message": "39"
            }